# docker-compose.yml

version: '3.4'

services:
  sample_1:
    image: sampleapp2_web_1:latest
    environment:
      - NODE_ENV=development
    command: npm start
    ports:
      - 3001:3000
    #volumes:
    #  - .:/app
